:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-spring-boot-for-azure

This article walks you through deploying a Spring Boot application to https://learn.microsoft.com/azure/spring-apps/overview[Azure Spring Apps].

IMPORTANT: You are recommended to check out https://learn.microsoft.com/azure/spring-apps/quickstart[Azure Spring Apps quick start doc] for the latest instructions for the same task.

== What you'll build

You'll clone a sample Spring Boot application from GitHub and then use Maven to deploy it to Azure Spring Apps.

== What you'll need

The following prerequisites are required in order to follow the steps in this article:

* An Azure subscription. If you don't have an Azure subscription, you can sign up for a https://azure.microsoft.com/pricing/free-trial/[free Azure account] or activate your https://azure.microsoft.com/pricing/member-offers/msdn-benefits-details/[MSDN subscriber benefits].
* An http://www.oracle.com/technetwork/java/javase/downloads/[Java Development Kit (JDK)], version 17 or later.
* A https://github.com/[Git] client.

== Build and run the web app locally

In this section, you will clone a Spring Boot application and test it locally.

. Open a terminal window.
. Create a local directory to hold your Spring Boot application by typing `mkdir SpringBoot`
. Change to that directory by typing `cd SpringBoot`.
. Clone the https://github.com/spring-guides/gs-spring-boot-for-azure[Deploying a Spring Boot app to Azure] sample project into the directory you created by typing `git clone https://github.com/spring-guides/gs-spring-boot-for-azure`
. Change to the directory of the completed project by typing `cd gs-spring-boot-for-azure/complete`
. Build the JAR file using Maven by typing `./mvnw clean package`
. When the web app has been created, start it by typing `./mvnw spring-boot:run`
. Test it locally by either visiting http://localhost:8080 or typing `curl http://localhost:8080` from another terminal window.
. You should see the following message displayed: *Hello World*.

== Config and deploy the app to Azure Spring Apps

=== Provision an Azure Spring Apps instance

. In a web browser, open the https://portal.azure.com/[Azure portal], and sign in to your account.
. Search for `Azure Spring Apps` and then select `Azure Spring Apps`.
. On the overview page, select Create, and then do the following:
  a. In the Service Name box, specify the name of your service instance. The name must be from 4 to 32 characters long and can contain only lowercase letters, numbers, and hyphens. The first character of the service name must be a letter, and the last character must be either a letter or a number.
  b. In the Subscription drop-down list, select the subscription you want to be billed for this resource.
  c. In the Resource group box, create a new resource group. Creating resource groups for new resources is a best practice.
  d. In the Location drop-down list, select the location for your service instance.
. It takes about 5 minutes for the service to be deployed.

=== Add configuration for deployment

. Config the web app with https://github.com/microsoft/azure-maven-plugins/tree/develop/azure-spring-apps-maven-plugin[Maven Plugin for Azure Spring Apps] by this command:
+
----
./mvnw com.microsoft.azure:azure-spring-apps-maven-plugin:1.16.0:config
----
+
 - This maven goal will first authenticate with Azure, if you have logged in with https://docs.microsoft.com/en-us/cli/azure/[Azure CLI], it will consume its existing authentication token. Otherwise, it will get you logged in with https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Maven-Plugin/[azure-maven-plugin] automatically.

 - After login successfully, you will get the subscription list like this:
+
----
Available subscription:
1. Demo Subscription A (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)*
2. Demo Subscription B (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
3. Demo Subscription C (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
... // Omit other subscriptions
Select subscription [1-xx] (1):
----
+
IMPORTANT: If there is error like `Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.` and get the subscription list successfully. You can just ignore the error and continue the following steps. Here is more information about this error: https://github.com/microsoft/azure-maven-plugins/issues/2270[azure-maven-plugins#2270].

 - Select the subscription which host the Azure Spring Apps you just created. Then you will get the Azure Spring Apps list:
+
----
Available Azure Spring Apps:
1. Sample-Azure-Spring-Apps-A*
2. Sample-Azure-Spring-Apps-B
3. Sample-Azure-Spring-Apps-C
... // Omit other Azure Spring Apps instance
Select Azure Spring Apps for deployment: [1-xx] (1):
----
+
IMPORTANT: If there is error like `does not support the API version '2022-09-01-preview'` and get the Azure Spring Apps instance list successfully. You can just ignore the error and continue the following steps. Here is more information about this error: https://github.com/microsoft/azure-maven-plugins/issues/2268[azure-maven-plugins#2268].

 - Configure other properties according to the hints:
+
----
[INFO] Using Azure Spring Apps: xxx
Input the app name (demo):
[INFO] There is only one valid runtime (Java 17) for your project, will use it automatically.
Expose public access for this app (boot-for-azure)? (y/N):
Summary of properties:
Subscription id   : xxx
Resource group name : xxx
Azure Spring Apps name : xxx
Runtime Java version : Java 17
App name          : demo
Public access     : true
Instance count    : 1
CPU count         : 1
Memory size(GB)   : 1
Confirm to save all the above configurations (Y/n):
[INFO] Configurations are saved to: gs-spring-boot-for-azure\complete\pom.xml
----
+
. Optionally, open the *pom.xml* to see the new added content.
+
----
<plugin>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-spring-apps-maven-plugin</artifactId>
    <version>1.16.0</version>
    <configuration>
        <subscriptionId>xxx</subscriptionId>
        <resourceGroup>xxx</resourceGroup>
        <clusterName>xxx</clusterName>
        <appName>demo</appName>
        <isPublic>true</isPublic>
        <deployment>
            <cpu>1</cpu>
            <memoryInGB>1</memoryInGB>
            <instanceCount>1</instanceCount>
            <runtimeVersion>Java 17</runtimeVersion>
            <resources>
                <resource>
                    <filtering/>
                    <mergeId/>
                    <targetPath/>
                    <directory>${project.basedir}/target</directory>
                    <includes>
                        <include>*.jar</include>
                    </includes>
                </resource>
            </resources>
        </deployment>
    </configuration>
</plugin>
----

=== Deploy the app

. Run this command to deploy the app:
+
----
./mvnw azure-spring-apps:deploy
----
+
. It might take a few minutes to deploy. After deploy finished, there will be a URL shown in the output. Navigate to the URL in a web browser. You should see the message displayed: `Hello World`.

== Summary

Congratulations! You built and deployed a Spring Boot app to Azure Spring Apps. You can visit the https://portal.azure.com/[Azure portal] to manage it.

IMPORTANT: Don't forget to delete the Azure resources created if no longer needed. 

== See also

Additional information about using Spring with Azure is available here:

* https://learn.microsoft.com/azure/developer/java/spring/[Spring on Azure]
* https://learn.microsoft.com/azure/developer/java/spring-framework/[Spring Cloud Azure]
* https://learn.microsoft.com/azure/spring-apps/quickstart[Deploy your first application to Azure Spring Apps]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/footer.adoc[]
