:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-spring-boot-for-azure

A Spring Boot hello-world application that includes everything you need to build and deploy an Azure solution. This application uses the Azure Developer CLI (azd) to get you up and running on Azure quickly. It includes application code and tools that serve as a foundation from which you can build upon and customize when creating your own solutions.

Let's jump in and get the hello-world app up and running in Azure. When you are finished, you will have a hello world app deployed on Azure.

IMPORTANT: You are recommended to check out https://learn.microsoft.com/azure/spring-apps/quickstart[Azure Spring Apps quick start doc] for the latest instructions for the same task.

== Prerequisites

The following prerequisites are required to use this application. Please ensure that you have them all installed locally.

- https://aka.ms/azd-install[Azure Developer CLI]
- https://learn.microsoft.com/en-us/java/openjdk/install[Java 17 or later]

== Quickstart

To learn how to get started with any template, follow the steps in https://learn.microsoft.com/azure/developer/azure-developer-cli/get-started?tabs=localinstall&pivots=programming-language-java[this quickstart] with this template.

This quickstart will show you how to authenticate on Azure, initialize using a template, provision infrastructure and deploy code on Azure via the following commands:

```bash
# Log in to azd. Only required once per-install.
azd auth login

# Enable Azure Spring Apps feature for AZD
azd config set alpha.springapp on

# First-time project setup. Initialize a project in the current directory, using this template.
azd init --template https://github.com/spring-guides/gs-spring-boot-for-azure

# Provision and deploy to Azure
azd up
```

== Application Architecture

This application utilizes the following Azure resources:

- https://docs.microsoft.com/azure/spring-apps/[**Azure Spring Apps**] to host the application

> This template provisions resources to an Azure subscription that you will select upon provisioning them. Please refer to the https://azure.microsoft.com/pricing/calculator/[Pricing calculator for Microsoft Azure] and, if needed, update the included Azure resource definitions found in `infra/main.bicep` to suit your needs.

== Application Code

This template is structured to follow the https://aka.ms/azure-dev/overview[Azure Developer CLI]. You can learn more about `azd` architecture in https://learn.microsoft.com/azure/developer/azure-developer-cli/make-azd-compatible?pivots=azd-create#understand-the-azd-architecture[the official documentation].

== Next Steps

At this point, you have a complete application deployed on Azure. But there is much more that the Azure Developer CLI can do. Using the Azure Developer CLI, you can delete the resources easily.

- https://learn.microsoft.com/azure/developer/azure-developer-cli/reference#azd-down[`azd down`] - to delete all the Azure resources created with this template

=== Additional `azd` commands

The Azure Developer CLI includes many other commands to help with your Azure development experience. You can view these commands at the terminal by running `azd help`. You can also view the full list of commands on our https://aka.ms/azure-dev/ref[Azure Developer CLI command] page.

=== Reporting Issues and Feedback
If you have any feature requests, issues, or areas for improvement, please https://aka.ms/azure-dev/issues[file an issue]. To keep up-to-date, ask questions, or share suggestions, join our https://aka.ms/azure-dev/discussions[GitHub Discussions]. You may also contact us via AzDevTeam@microsoft.com.

== See also

Additional information about using Spring with Azure is available here:

* https://learn.microsoft.com/azure/developer/java/spring/[Spring on Azure]
* https://learn.microsoft.com/azure/developer/java/spring-framework/[Spring Cloud Azure]
* https://learn.microsoft.com/azure/spring-apps/quickstart[Deploy your first application to Azure Spring Apps]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/footer.adoc[]
